### PR TITLE
Add Python 3.12 images

### PR DESCRIPTION
**Pull request by jacobtomlinson**
Add Python 3.12 images.

### CODE REVIEW

**Comment by jacobtomlinson** [comment]
It looks like there is some issue with `python-blosc` in the 3.12 notebook images. 

@jrbourbeau do you have any thoughts on how we can fix this failed solve?

**Review by jrbourbeau — COMMENTED** [review]
Thanks @jacobtomlinson for adding this

It should be safe to just drop it as `distributed` dropped support for blosc a while ago (xref https://github.com/dask/distributed/pull/6027)

**Comment by jacobtomlinson** [comment]
Things look good, merging!

**Comment by jrbourbeau** [comment]
Thanks @jacobtomlinson

**Comment by jacobtomlinson** [comment]
Sure thing!

**Pull request merged**
