### PR TITLE
Bump dask to 0.19.4 and use defaults channel

### PR DESCRIPTION
**Pull request by mrocklin**

### CODE REVIEW

**Comment by danielfrg** [comment]
Is it worth it to remove `conda-forge` from the notebook image `.condarc`?

**Comment by mrocklin** [comment]
> Is it worth it to remove conda-forge from the notebook image .condarc?

The objective here would be to avoid future conda-forge installs if the user conda installs something?

**Comment by mrocklin** [comment]
I'm just going to switch to conda-forge for this release.  I'll investigate sizing issues and bring it up with the conda-forge community.

**Comment by mrocklin** [comment]
Oh man, the difference is even more pronounced with an updated miniconda base image

```
daskdev/dask             0.19.4              b00c41c7d47d        About a minute ago   1.15GB
daskdev/dask             0.19.4-defaults     51e1a809e886        3 minutes ago        590MB
```

**Comment by mrocklin** [comment]
I've raised https://github.com/conda-forge/pandas-feedstock/issues/54 upstream as an example issue.  I'm going to dig a bit more

**Pull request merged**
