### PR TITLE
RLS: Bump to 2.0

### PR DESCRIPTION
**Pull request by TomAugspurger**

### CODE REVIEW

**Comment by mrocklin** [comment]
This seems like an improvement to me.  

The other thing we might consider is the jupyter-lab situation.  We had issues with the dask-examples setup and recent jupyter-labs, but this might have been with development versions.  My guess is that things are fine as long as we stable though, and that we'll probably have another Dask release shortly after the JLab 1.0 release occurs.

**Comment by TomAugspurger** [comment]
Yeah, I'm trying to keep up with the jupyterlab changes for pangeo. I'm planning to try out a jupyterlab 1.0rc deployment today if I have time.

**Comment by mrocklin** [comment]
@ian-r-rose has been keeping the environment in dask-examples up to date
with recent release candidates

**Comment by mrocklin** [comment]
If you wanted an example to steal from

**Comment by jacobtomlinson** [comment]
I would find it useful if we could get this in and a new release done. It would also be good to keep this up to date with dask releases.

I would be happy to automate this.

**Comment by TomAugspurger** [comment]
Automating this as part of the release process would be nice.

---

I've also bumped

- dask-labextension -> 1.0.0
- jupyter-widgets/jupyterlab-manager (js) -> 1.0.1

**Comment by TomAugspurger** [comment]
Whoops, don't merge this yet. There's a version conflict.

**Comment by TomAugspurger** [comment]
Ah, it was a stale version of `jupyter/base-notebook` that our notebook image derives from. I'm not a docker expert, but should we be pinning that to a specific version?

**Comment by TomAugspurger** [comment]
Anyway, this should be good to go, but I would appreciate a +1 from someone more knowledgeable about docker things (@jacobtomlinson?)

**Comment by jacobtomlinson** [comment]
Looks like `graphviz ` got lost here, is that intentional?

**Comment by jacobtomlinson** [comment]
Raised #52 so that automation action doesn't get lost.

**Comment by TomAugspurger** [comment]
Unintentional. Fixed now.

**Comment by jrbourbeau** [comment]
Is this good to merge then?

**Comment by TomAugspurger** [comment]
Should be, thanks.

**Comment by jrbourbeau** [comment]
Thanks all!

**Pull request merged**
