### PR TITLE
feature added to save JupyterLab work and added windows docker patch

### PR DESCRIPTION
**Pull request by anorak4**

### CODE REVIEW

**Review by jacobtomlinson — CHANGES_REQUESTED** [review]
Thanks for raising this @anorak4. I'm not sure these changes will benefit everyone though.

You seem to have commented out the base notebook build, which we do explicitly so that we can control the Python version being installed.

You have also created a volume mapped to a local relative path. I agree that having a volume for this work makes sense, but it is best practice [to use a named volume](https://docs.docker.com/storage/volumes/#create-and-manage-volumes) rather than a path.

**Comment by anorak4** [comment]
Thanks for the candid feedback, @jacobtomlinson . I will look into some alternatives that would work on windows docker without trying to eliminate how the Python version is being controlled. 

For the volume mount, I understand that it is best practice to use named volume but doesn't look like there is an easy way to achieve that with docker-compose. I will look into that as well. 

Thanks.

**Comment by jacobtomlinson** [comment]
I am curious what the motivation is to build on Windows. We already publish these container images to Docker Hub from our CI environment. Why are you trying to build them locally?

Volumes are quite common in docker-compose. See the [documentation here](https://docs.docker.com/compose/compose-file/compose-file-v3/#volumes).

**Comment by jacobtomlinson** [comment]
I'm going to close this out due to inactivity. If you want to continue with this PR let me know and I'll reopen it.

**Pull request closed without merging**
