### PR TITLE
Add `jupyter-server-proxy`

### PR DESCRIPTION
**Pull request by jacobtomlinson**
Added `jupyter-server-proxy` to enable being able to view the worker dashboards by default.

### CODE REVIEW

**Comment by mrocklin** [comment]
In principle this seems like a good idea.  My one concern would be an increased image size.

```
(dev) MROCKLIN-MLT:~ mrocklin$ conda create -n foo -c conda-forge dask-core distributed
(dev) MROCKLIN-MLT:~ mrocklin$ conda activate foo
(foo) MROCKLIN-MLT:~ mrocklin$ du -hs miniconda/envs/foo/
134M	miniconda/envs/foo/
(foo) MROCKLIN-MLT:~ mrocklin$ conda install -c conda-forge jupyter-server-proxy
(foo) MROCKLIN-MLT:~ mrocklin$ du -hs miniconda/envs/foo/
308M	miniconda/envs/foo/
```

Adding this to the dask-notebook image seems like an obviously good choice.  Adding it to the base image seems less exciting, but maybe still a good idea.

**Comment by jacobtomlinson** [comment]
Oof that is far larger than I expected. What on earth is taking up all that space?

Sadly adding it to the notebook isn't really going to help in the situations where it would be useful for me (scheduler pod in dask-kubernetes).

**Comment by mrocklin** [comment]
Well, it depends on jupyter-core, which brings in lots of things.  We might consider vendoring in the parts that we need and removing the jupyter dependency.  cc @yuvipanda any thoughts?

> Sadly adding it to the notebook isn't really going to help in the situations where it would be useful for me (scheduler pod in dask-kubernetes).

Yeah...

**Comment by yuvipanda** [comment]
Yeah, I'd love to factor out the proxy parts into their own thing that just depends on tornado, and have jupyter-server-proxy depend on that as a library. Is probably not difficult to do, just a 'matter of finding the time'. The only difficult setup would be 'how do we do authentication?', since the Jupyter parts handle that now. Would be happy to review and merge if someone were to do this :)

**Comment by mrocklin** [comment]
Also cc'ing @jcrist , in case he is interested in this topic.

**Comment by martindurant** [comment]
Checking up on old issues - is there any interest in pushing this forward?

**Comment by jacobtomlinson** [comment]
I think in order to get this in `jupyter-server-proxy` needs to be refactored to drop Jupyter as a dependency. 

As that's probably unlikely in the short term I'm inclined to close this.

**Pull request closed without merging**
