### PR TITLE
New libs and version explicit

### PR DESCRIPTION
**Pull request by lbonini94**
Added some libs and explicit versions to avoid MissMatch versions warning on jupyter-dask

### CODE REVIEW

**Comment by lbonini94** [comment]
image

**Review by TomAugspurger — COMMENTED** [review]
What's the motivation for adding dask-ml and matplotlib to the base image? IMO not enough people need these to warrant including them.

**Comment by lbonini94** [comment]
I think it's more common to use the image for dev or testing with the sample notebooks than to use it in a production environment (in these cases, unused libraries will certainly be reviewed and removed by the devops team). When I start the service with docker-compose the way it is, version mismatch happens and the example notebooks don't run.

**Comment by jacobtomlinson** [comment]
I agree that adding `dask-ml` and other packages will increase the image size for little benefit to others. I'm not sure how much this things are actually used.

I also expect these hard pins will go out of date quickly as the Jupyter images change outside of our control.

**Comment by jacobtomlinson** [comment]
Things have changed a lot in #166 and #149 so I'm not sure this PR makes sense anymore. Plus there hasn't been any activity here for a number of weeks. Thanks for your efforts @lbonini94.

**Pull request closed without merging**
