### PR TITLE
Bump versions to distributed 1.21.4

### PR DESCRIPTION
**Pull request by ogrisel**
The two Dockerfiles of this repo where not updated in sync.

BTW, how are the docker images pushed to dockerhub and how is the tag of the image selected? Manually?

### CODE REVIEW

**Comment by mrocklin** [comment]
I've also just pushed a version 1.21.5 to PyPI and conda-forge

> BTW, how are the docker images pushed to dockerhub and how is the tag of the image selected? Manually?

I'm actually not sure. I wouldn't be surprised if things were still manual.  This could be improved ...

**Comment by danielfrg** [comment]
Both docker repos are configured as automatic builds on dockerhub so they get built automatically. As for the tags, `master` will be tagged as `latest` and other git tags will be tagged as that.

**Comment by ogrisel** [comment]
Would it be possible to automatically tag with the dist 6 digits of the git commit digest as done by the jupyterhub crew?

That would require some manual garbage collection for very old images though.

**Comment by danielfrg** [comment]
I don't think this is possible based on the options I see on the automated build settings and on this unanswered question: https://stackoverflow.com/questions/41355911/how-to-tag-docker-hub-automated-builds-as-git-sha

But if you know how to do that i will be happy to add it.

**Comment by danielfrg** [comment]
Do you know if the jhub people do it automatically or they push that manually with everytag?

**Comment by ogrisel** [comment]
No idea. Maybe it's not possible.

**Pull request merged**
