### PR TITLE
Add support for environment.yml and helper notebook container

### PR DESCRIPTION
**Pull request by danielfrg**
Based on feedback at https://github.com/dask/dask-docker/issues/2

I added basic support for `environment.yml` and created another `Dockerfile` to support the same functionality on the notebook server this should help us match dependencies better. Any feedback would be great @ogrisel.

For the notebook image I think it would be nice to add some default example notebooks any ideas for that @mrocklin?

### CODE REVIEW

**Comment by ogrisel** [comment]
I am wondering: maybe we should try to consolidate this effort with the developers of the jupyterhyb docker-stacks.

In many cases you would like to ensure that the Python environment in the jupyter kernel that access the dask cluster (using `distributed.Client`) is the same as the Python environment of the dask workers (and possible the scheduler as well to keep things as simple as possible).

**Comment by ogrisel** [comment]
Apparently the jupyterhub devs would recommend to use https://github.com/jupyter/repo2docker to customize the images used by the jupyter kernels.

**Comment by ogrisel** [comment]
More details on the helm-based jupyterhyb setup: https://zero-to-jupyterhub.readthedocs.io/en/latest/create-k8s-cluster.html

**Comment by danielfrg** [comment]
I am going to merge this so we can at least fix the default Helm but we should change the notebook iamge to use repo2docker in the future.

**Pull request merged**
