### PR TITLE
ENH: cache installing of deps

### LINKED ISSUE #107: Cache user-specified dependencies
I have an `environment.yml` file. It installs 13 packages from conda and 23 packages from PyPI. Installing takes time. It'd be nice if this could be accelerated on repeated builds. I think this would be possible by caching the downloads/installs.

### PR DESCRIPTION
**Pull request by stsievert**
**What does this PR implement?**
This PR runs the installing of dependencies as a separate Docker command.

**Reference issues/PRs**
This PR resolves #107.

### CODE REVIEW

**Comment by jacobtomlinson** [comment]
I appreciate the effort here, however I feel it may be better to create your own Docker images with your dependencies already installed.

We are beginning to replicate what Docker is already doing.

**Comment by stsievert** [comment]
> create your own Docker images with your dependencies already installed.

That's what I've done. I opened this PR because my implementation is basically replicating the implementation in this PR; all my Docker image really does is activates `environment.yaml`.

**Comment by stsievert** [comment]
For a simple use case, there still might be significant downloads. For example, if I mirror PyTorch's installation instructions in my `environment.yml` file, Docker downloads more than 800MB. Here's how much each downloaded packaged downloads:

* PyTorch 1.5.1 (no deps): 433 MB
* cudatoolkit (no deps): 347MB

This is a nice if these could be downloaded with native Docker commands  (i.e, `RUN bash install-deps.sh `) instead of a custom script. That'd allow Docker to cache the output/machine state after `bash install-deps.sh`.

**Comment by jacobtomlinson** [comment]
Another challenge I can see here is that the dependency installation will now run as root. Which will likely break subsequent installs as the jovyan user at runtime.

**Comment by stsievert** [comment]
> This could be done by calling install-deps.sh from the prepare.sh script.

Would this cache the 800MB download? Doesn't Docker run the entrypoint (`prepare.sh`) each time? I believe Docker caches the state before `prepare.sh` is called, not any of the downloads that happen after the entrypoint is executed. Is that correct, and if not, why?

**Comment by jacobtomlinson** [comment]
> Would this cache the 800MB download?

If the docker image had been built with the environment variables already set then yes this would cache the download the first time `install-deps.sh` is called during the build.

Then with that bespoke image whenever it starts it would call `prepare.sh` which in turn would call `install-deps.sh`. But `install-deps.sh` would no nothing because everything is already installed.

However if folks are using the `daskdev/dask:latest` image, or some other generic build then their dependencies would be installed during `prepare.sh` every time.

Also user's may decide to call `conda/pip install` from within their notebook or python session and install extra stuff on the fly.

I think we need to ensure we support all three use cases, and any combination of them.

> I believe Docker caches the state before prepare.sh is called

Every command in the Docker file ('RUN', 'COPY', etc) causes a layer to be cached. Docker effectively uses [`tar --incremental`](https://www.gnu.org/software/tar/manual/html_node/Incremental-Dumps.html) to create archives of the diff from each command. Then each archive is unpacked over each other in layers.

So you're right that things are cached before `prepare.sh` is called. But this change breaks the current behaviour for folks who are not interested in caching during the build.

**Comment by jacobtomlinson** [comment]
I'm going to close this out as there has been no activity here for some time.

**Pull request closed without merging**
