### PR TITLE
Bump dask to 0.18.1

### PR DESCRIPTION
**Pull request by Tautvis**
And distributed to 0.12.0

### CODE REVIEW

**Comment by mrocklin** [comment]
Looks good.  Thanks @Tautvis !

**Comment by Tautvis** [comment]
Hi @mrocklin , do you mind telling me what triggers tagging image (https://hub.docker.com/r/daskdev/dask/tags/) with a different tag than 'latest'?

**Comment by mrocklin** [comment]
My guess is that we don't have any infrastructure for this today.  I've been doing this manually for the last few months.  However it would be very good to make this process more automated.  If you have suggestions, or any desire to set this up, both or either would be very welcome.

**Comment by Tautvis** [comment]
I looked at docker hub automated builds and it supports tagging images with branch names or tags. I suggest labelling docker images by release tags and using latest tag for master branch. Like this:
image
Could you made this change to the docker hub automated build and then I'll try to tag latest commit which should trigger image build with a label.

**Comment by mrocklin** [comment]
Done.  Also pushed a tag.  It seems to be building now.

**Comment by Tautvis** [comment]
Thanks! 👍

**Comment by mrocklin** [comment]
Thanks for figuring out what to do!

**Pull request merged**
